apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
patches:
- path: ./dev-patch-deploy.yaml
- path: ./dev-patch-service.yaml
images:
- name: service-image
  newName: kubrabkaf/kubrabkaf
  newTag: 0.0.1
