FROM golang:1.21.4 as build_kubrabkafka
ENV CGO_ENABLED 0
ARG BUILD_REF

COPY . /service

WORKDIR /service/cmd
RUN go build -ldflags "-X main.build=${BUILD_REF}"

FROM alpine:3.18
ARG BUILD_DATE
ARG BUILD_REF

# Add permissions for non-root container user.
RUN addgroup -g 1000 -S kubrabkafka && \
		adduser -u 1000 -h /cmd -G kubrabkafka -S kubrabkafka

COPY --from=build_kubrabkafka --chown=kubrabkafka:kubrabkafka /service/cmd/cmd /service/cmd
WORKDIR /service
RUN echo ls

USER kubrabkafka
CMD ["./cmd"]