apiVersion: v1
kind: Namespace
metadata:
  name: kubrabkaf-infra

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubrabkaf
  namespace: kubrabkaf-infra

spec:
  selector:
    matchLabels:
      app: kubrabkaf

  template:
    metadata:
      labels:
        app: kubrabkaf

    spec:
      terminationGracePeriodSeconds: 60

      containers:
      - name: kubrabkaf
        image: kubrabkaf

        ports:
          - name: kubrabkaf
            containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: kubrabkaf
  namespace: kubrabkaf-infra